### ISSUE TITLE
v0.0.3 still using old build

### ISSUE THREAD

**Issue by yanshiyason** [ksivamuthu/aws-copilot-github-action#178]
Hi @ksivamuthu,

It seems like the latest release is not actually using the latest code. If you download the zip file and look at the `/lib/main.js` file, you can see that the code is for an older version.

https://github.com/ksivamuthu/aws-copilot-github-action/archive/refs/tags/v0.0.3.zip

Would it be possible to release a new build with the latest compiled code?

I am not sure what the procedure is to update the build 🤔 ..

Thank you!

**Comment by yanshiyason** [comment]
I think it is necessary to run `npm run build && npm run package` and then release a new tag.

**Comment by ksivamuthu** [comment]
@yanshiyason  Repackaged. I'm adding it to github actions to avoid this in future releases. Thanks.

**Comment by yanshiyason** [comment]
Thank you very much @ksivamuthu ! Much appreciated :)
