### ISSUE TITLE
AWS Copilot 1.30.0 breaks this action

### ISSUE THREAD

**Issue by Offlein** [ksivamuthu/aws-copilot-github-action#194]
Hi,

This action by default will load the latest, as of today, Copilot (1.30.0) which now prompts you for whether you want to deploy your environment before deploying the app. (Which is a confusing concept to me, but that's whatever.)

Anyway, all of our builds now hang on `ksivamuthu/aws-copilot-github-action` because it's waiting for prompt.

Issue #193 would help work around this, but it looks like this is something the action will need to be prepared for in a general sense.

Maybe more importantly: for some reason I get no visibility into this step in my Github Actions UI until I cancel the run, at which point I can see that it was just sitting and waiting interminably for a Y/N input.

If there's any way you can easily make the action properly output everything it's doing, that would help future users! :pray: 

...Now off to complain to AWS, who not only broke people's automated builds but deploy process throws an error because I wrote bad YAML while following [their own incorrect documentation](https://aws.github.io/copilot-cli/docs/manifest/environment/#network-vpc-security-group-egress). (Note the flip-flopping between `security-group` and `security_group`...)

**Comment by vmarksabelita** [comment]
I am having the same issue, any resolution for this ?

**Comment by vmarksabelita** [comment]
resolved this by adding version to the yml file

`
- uses: ksivamuthu/aws-copilot-github-action@v0.0.7
        with:
          command: deploy
          app: appname
          env: test
          force: true # optional
          version: v1.29.1
          `

**Comment by Offlein** [comment]
@vmarksabelita Thanks so much for the tip.

I'll update our yml!

(And fwiw it looks like AWS [is fixing this](https://github.com/aws/copilot-cli/pull/5262) on their end in a general sense as well.) Possibly as I'm writing this! So maybe @ksivamuthu might not need to effect any changes.

**Comment by grevian** [comment]
Thanks @vmarksabelita this helped me too, AWS has merged and released what the intended fix was as [1.30.1](https://github.com/aws/copilot-cli/releases/tag/v1.30.1), but it still seems to impact this workflow, your suggestion to pin the previous version works just fine though

**Comment by PauloFerreira25** [comment]
Current version is v1.33.4.
If the bug remains, we will reopen.
